### ISSUE TITLE
linear-gradient

### ISSUE THREAD

**Issue by pedolsky** [AnthonMS/ha-slider-card#22]
Hi,

thank you so much for your work. It would be great if we could add `linear-gradient` as a color option, especially when slider function `Warmth` is used.

**Comment by AnthonMS** [comment]
Yeah I agree, this could be nice. But right now I'm using the standard Input Range Element, and this makes styling the progress bar extremely difficult. Since the progress bar is technically 1 very large square box, where it is hidden by the sliders overflow setting.

I am planning on playing around with some npm slider packages, now that the card has been updated to use npm.

**Comment by AnthonMS** [comment]
This repo has been archived, becuase of some major changes breaking peoples setups. 

Read the readme to find new repo link. You are more than welcome to make this issue on the new repo.

**Comment by pedolsky** [comment]
Ok for me 👍🏻
