### ISSUE TITLE
Last update to repository seems to be broken

### ISSUE THREAD

**Issue by Paddy0174** [AnthonMS/ha-slider-card#24]
The last update to this repository seems to be broken.

Just on a first small look, the `readme.md` doesn't reflect the actual changes, despite from the "Breaking Change" part. And the `package.json` seems to be wrongly copied from `my-button`.

Therefor the installation/update with HACS seem to delete the old folder (and *.js file), but doesn't download and install the new version. There is no message in the logs.

I didn't search more closely, as I assume there went something wrong with your repositories (mix up with `my-button`).

Please take a look!

**Comment by AnthonMS** [comment]
my-button is just another card I have been working on. That's why I have copied it, I forgot to change the name there.

I have updated HACS.json to take into account that the new .js file is in the dist/ directory. And I did test it out by installing the card with hacs on my own system, and that worked without a problem and that is what I am using now. So it sounds weird if it just uninstalled the old card without installing the updated one with you..

And I agree, I should update the readme. But I finished this late last night, and I thought people would be happy about the change, where the card is not cloud dependant anymore. And I don't know when I'll have time to look at the card again. 
And I do say breaking change in the top of the readme, I think people can figure out, they need to change "custom:slider-card" to "custom:my-slider" and their resource by that statement.

**Comment by nomis-on** [comment]
I just had the same issue. It seems you first need to uninstall the old integration and ALSO remove the custom repository url. Only then after adding this repository to HACS again it successfully created the installation folder and also the install information (what to add to the lovelace resource configuration) was updated to "...my-slider.js".

**Comment by AnthonMS** [comment]
Okay, I'm imagining it's because hacs thinks the .js file is still in the root of the repo, like it was before the changes.

I don't know what I can do to help smooth things over for other people wanting to update the card. Other than just add this to the top of the readme.

**Comment by pedolsky** [comment]
Last night my internet went away and it was the first time I recognized the dependency on working dsl connection. So thank you SO much for this update and your beautiful work!

I don’t use HACS, I use manual installation, but the most important thing was to **empty the cache.**

**Comment by AnthonMS** [comment]
> So thank you SO much for this update and your beautiful work!

You're very welcome! Appreciate the positive feedback! 
I have been wanting to make this update for a long time, and finally got around to it.

**Comment by Paddy0174** [comment]
The idea behind the update is great, and I'm quite sure I'm not the only one who was eagerly waiting for that update. Thank you for that, it makes a good card great. :) 

But the way you did this update is not very amusing. It simply is not ready yet for an update. You killed the possibility to use it via HACS. That the new installation worked for you, seems to be a cache issue on your side. 

If you start with a fresh installation, you can't even add the repository, because HACS is scanning for a file, that simply is not there. One of the rules with HACS and lovelace cards (called plugins in HACS) is, that the name of the file has to match the name of the repository. In this case `ha-slider-card` vs. `my_slider`....

Don't get me wrong, I can see the point, where one has no time and one wants to finish some work. But hurrying through this is not the right way. If you don't have the time, than leave the update alone. If you publish it, people are assuming everything is working. And that includes at least an updated readme file, that is fitting the repository it is shown in. The actual readme has two paragraphs about installation, one from `my_button` and one from `ha-slider-card` (note, not `my_slider`). The `package.json` file still has the wrong component in it.

All in all, what you have done is great work, but you haven't had it finished, before you published the update. 

I'm sorry to say, but this update should be rolled back and afterwards should be done correctly. As I said, nobody is hurrying you to anything, but if you do it, do it right. If you don't have the time, than leave it alone and work on it, when you get the time. And if this point never arrives, so be it. But sending people on a wild goose chase for the reason why there carefully crafted frontend isn't working anymore is not the way to go. 

My suggestion would be to roll back the update, start a new repository with the correct conventions from HACS and archive this repository after a while. Would have made things way easier and straightforward from the beginning. 

Sorry, just my two cents... ;)

**Comment by AnthonMS** [comment]
Yeah I agree it was rushed. And the only reason I didn't rollback last night, was because it was working for me. 
And let me just say, I didn't have the repo in hacs before last night, I developed right in the plugins folder and copy pasted the updated card to the GitHub repo, so there has never really been version control. And the reason for that was, I made this card for myself. I didn't think people would actually use it. 

I don't think there is any way of updating this repo anymore then, since the structure will not go back to what it was. Since it was only the card and a hacs file.

And I'm sorry to say this, but if this didn't work. I don't think there is a right way of updating the repo to have the new structure.

And last thing, I haven't made this card for anybody, but myself. I am happy if other people can use it. But that's not the reason made it in the first place.

And yes, I will be making a new repository, but not because of this card. But because I am working on some other cards and this will be a bundle of my cards. 

I'm not gonna roll this back, because it doesn't sound like a caching issue on my machine. But a caching issue on the machines where people have already installed it via. HACS. 

And yes the readme has 2 install methods, it's notes for myself so I remembered to update it with new install instructions...
But if you don't like that, then I can just remove the readme all together, since I know how to install and use it? 


And just a heads up, I will be making some other breaking changes in the near future. So maybe you should just not update it right now, since you dislike breaking changes so much. Breaking changes are never fun, but I will not hold back an update for my own card, because some people don't like uninstalling and reinstalling the card for this major change.

And there you go, because you can't see past the missing updates in the readme and package.lock, they have now been updated...

**Comment by AnthonMS** [comment]
I have rolled it back and started a new repo. I hope this is to your liking...

I will close all issues on this repo, because I'm not gonna work on this anymore.
