### ISSUE TITLE
Support adjustable speed fans

### ISSUE THREAD

**Issue by phrz** [AnthonMS/ha-slider-card#3]
Hello, thank you for this great add-on! I'm trying to make heavy use of it and have a few issues to submit, but will space them out to avoid being a pain. 

This issue is more of a feature request: I would like to use `slider-card` with adjustable speed fan entities. Before this add-on, I used [slider-entity-row](https://github.com/thomasloven/lovelace-slider-entity-row), which supports adjusting light brightness, fan speed, or any adjustable attribute you throw at it (such as LED hue and saturation). I only reference them as an example, but their code may offer some insight on supporting a broader array of adjustable properties.

Below are pictures of `slider-entity-row` in use for fans and the incompatibility of fans with `slider-card`.

<img width="285" alt="Screen Shot 2021-04-16 at 11 20 35" src="https://user-images.githubusercontent.com/2007088/115054380-c5304700-9ea5-11eb-9de7-5d77fb6e912f.png">

<img width="510" alt="Screen Shot 2021-04-16 at 11 19 18" src="https://user-images.githubusercontent.com/2007088/115054213-99ad5c80-9ea5-11eb-9c1a-98911f036968.png">

If you are able to make this work it would be amazing. Also if I can compensate in exchange for dealing with my other issues/wishlist items for this add-on, email me at "m [at] x63 [dot] me." Thanks again!

**Comment by AnthonMS** [comment]
Hey, sorry for not responding quicker. Life gets in the way, you know how it is.

The reason your examples are not supported, is simply because I have not had the need for them. I will add support for different entity types and attributes when people ask me to add support for them or I stumple across them myself. 

So the next time I have time for it, I will definitely add adjustable fan control. I will update you and close this issue when it is done.

And thanks for liking the card, I'm happy that other people get good use of it. :)

**Comment by AnthonMS** [comment]
If you want to make it faster for when I look into it, post some screenshots of the attributes of the fan, send some in different states.

**Comment by AnthonMS** [comment]
I was sitting at my computer and waiting for a 3D print. Try it, I am not sure it will work, since I don't have a fan, so I don't know how the attributes look precisely. but it would be nice if it just worked. 
And please just ask for features, don't feel like you are asking for too much. If I don't want to add a feature, I will say so :)
